(() => {
 'use strict';
 const D=window.AI_CONTENT;
 const C=window.AI_SITE_CONFIG||{};
 const state={lang:'zh',habit:'think',light:'green',q:0,answers:[],stage:'before',checks:{},checkResult:false,form:{light:'',verifyStatus:''},generated:false};
 const app=document.getElementById('app');
 const tr=(zh,en)=>state.lang==='zh'?zh:en;
 const tx=o=>o[state.lang];
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const route=()=>['practice','check','declaration'].includes(location.hash.slice(1))?location.hash.slice(1):'guide';
 const source=s=>`<p class="source-ref">${tr('指引依據','Policy reference')} · ${esc(tx(s))}</p>`;
 const arrow='<span aria-hidden="true">↗</span>';
 const mark='<img src="assets/mark.svg" width="40" height="40" alt="">';
 const selectOptions=(options,value)=>options.map(([v,label])=>`<option value="${v}" ${v===value?'selected':''}>${esc(label)}</option>`).join('');
 const navItems=[['guide',tr('讀懂指引','Learn the guide')],['practice',tr('情境練習','Try scenarios')],['check',tr('快速自查','Self-check')],['declaration',tr('課業聲明','Disclosure')]];
 const nav=()=>navItems.map(([id],i)=>{const names=[tr('讀懂指引','Learn the guide'),tr('情境練習','Try scenarios'),tr('快速自查','Self-check'),tr('課業聲明','Disclosure')];return `<a href="#${id}" ${route()===id?'aria-current="page"':''}><span class="nav-num">0${i+1}</span>${names[i]}</a>`;}).join('');

 function shell(content){
  return `<header class="header"><div class="header-inner"><a href="#guide" class="brand" aria-label="${tr('LIY學生數字素養計劃入門階段首頁','LIY Student Digital Literacy Programme Foundation Stage home')}">${mark}<span><strong>${tr('LIY學生數字素養計劃','LIY Student Digital Literacy')}</strong><small>${tr('入門階段｜人工智能素養基礎證書','Foundation Stage · AI Literacy Foundation Certificate')}</small></span></a><div class="header-tools"><button class="language" data-action="language" aria-label="${tr('Switch to English','切換至繁體中文')}">${tr('EN','繁中')} <span aria-hidden="true">◎</span></button></div></div><nav class="top-nav" aria-label="${tr('主要導覽','Main navigation')}">${nav()}</nav></header>
  <main id="main" tabindex="-1">${content}</main>
  <footer class="footer"><div><strong>${tr('育人為本，科技為輔。','People first. Technology in support.')}</strong><p>${esc(tx(D.school))}</p></div><div><p>${tr('依據《校本人工智能學習與使用指引》稿 v1','Based on the School AI Learning and Use Guidelines, draft v1')}</p><p>${tr('學生學習試用版；英文為輔助翻譯，以中文初稿為依據。','Student learning preview. English is a supporting translation of the Chinese draft.')}</p><p>${tr('不用登入。輸入與練習只留在本次頁面，重新整理後清空。','No sign-in. Entries and practice stay on this page and clear on refresh.')}</p><button class="text-link" data-action="reset-all">${tr('清除本次所有答案與表格','Clear all answers and entries')}</button></div></footer>`;
 }
 function guide(){
  const h=D.habits.find(x=>x.id===state.habit),l=D.lights.find(x=>x.id===state.light);
  return `<section class="hero wrap"><div class="hero-copy"><p class="eyebrow">LIY · STUDENT DIGITAL LITERACY · FOUNDATION STAGE</p><h1>${tr('善用 AI，<br>把思考留給自己。','Use AI.<br>Keep your thinking.')}</h1><p class="hero-desc">${tr('這是「LIY學生數字素養計劃」的入門階段。全體學生均應完成本階段的指定學習並通過測驗，取得「人工智能素養基礎證書」。AI 可以是學習夥伴；懂得先想、查證、申報，有疑問便問。','This is the foundation stage of the LIY Student Digital Literacy Programme. All students are expected to complete the designated learning and pass the assessment for the AI Literacy Foundation Certificate. AI can be a learning partner: think first, verify, disclose, and ask when unsure.')}</p><div class="hero-actions"><a class="button primary" href="#habits">${tr('從四個習慣開始','Start with four habits')} <span aria-hidden="true">↓</span></a><a class="text-link" href="#practice">${tr('試試情境練習','Try a scenario')} ${arrow}</a></div><div class="values">${D.principles.map((p,i)=>`<span><i aria-hidden="true">${['◇','◎','✳'][i]}</i>${esc(tx(p))}</span>`).join('')}</div></div>
  <div class="hero-art" aria-label="${tr('先想、查證、申報、有疑問便問四個學習習慣','Four learning habits: think, verify, disclose and ask')}"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><span class="art-star" aria-hidden="true">✳</span><div class="art-top">LEARN WITH AI / THINK FOR YOURSELF</div><div class="habit-paper"><span class="paper-label">MY LEARNING NOTES</span><h2>${tr('學習的主角，<br>仍然是你。','You are still<br>the learner.')}</h2>${D.habits.map((x,i)=>`<div class="paper-line"><span>0${i+1}</span><b>${esc(tx(x.label))}</b><span aria-hidden="true">${['↗','◎','✎','?'][i]}</span></div>`).join('')}</div><div class="art-bottom"><span class="art-dots"><i></i><i></i><i></i></span>${tr('看任務，不只看工具。','Look at the task, not just the tool.')}</div></div></section>
  <div class="reading wrap"><aside class="reading-nav"><p class="eyebrow">${tr('這一頁學甚麼','ON THIS PAGE')}</p><a href="#habits">01　${tr('四個基本習慣','Four habits')}</a><a href="#lights">02　${tr('三燈使用框架','Three-light framework')}</a><a href="#protect">03　${tr('負責任使用','Use responsibly')}</a><a href="#disclose">04　${tr('說清楚 AI 的協助','Explain AI’s role')}</a><div class="side-note"><span aria-hidden="true">↳</span><p>${tr('善用科技、駕馭科技，<br>而不依賴科技。','Use technology well.<br>Stay in control.<br>Avoid dependence.')}</p></div></aside>
  <div class="reading-body"><section id="habits" class="guide-section"><div class="section-heading"><span class="section-no">01</span><div><p class="eyebrow">A HABIT BEFORE A TOOL</p><h2>${tr('四個習慣，一直用得上。','Four habits to carry with you.')}</h2></div></div><p class="section-intro">${tr('先想 → 查證 → 申報 → 有疑問便問。點選一個習慣，看看下一步可以怎樣做。','Think → Verify → Disclose → Ask when unsure. Select a habit to see a practical next step.')}</p>
  <div class="habit-tabs" role="tablist" aria-label="${tr('四個習慣','Four habits')}">${D.habits.map((x,i)=>`<button id="tab-${x.id}" role="tab" aria-selected="${x.id===h.id}" aria-controls="habit-panel" tabindex="${x.id===h.id?0:-1}" data-habit="${x.id}"><span>0${i+1}</span>${esc(tx(x.label))}</button>`).join('')}</div><div id="habit-panel" class="habit-panel" role="tabpanel" aria-labelledby="tab-${h.id}" tabindex="0"><h3>${esc(tx(h.title))}</h3><p>${esc(tx(h.body))}</p><div class="next-step"><span>${tr('試著這樣做','TRY THIS')}</span><p>${esc(tx(h.action))}</p></div>${source(h.source)}</div></section>
  <section id="lights" class="guide-section"><div class="section-heading"><span class="section-no">02</span><div><p class="eyebrow">THE TASK SETS THE BOUNDARY</p><h2>${tr('這次任務，亮甚麼燈？','Which light applies to this task?')}</h2></div></div><p class="section-intro">${tr('燈號針對「學習任務」，不是某一項 AI 功能。同樣是語文潤飾，在專題報告中可能容許，在評估語文表達能力時卻可能受限。','The light applies to the learning task, not to an AI feature. Proofreading may be permitted in a project report but restricted when your language ability is being assessed.')}</p>
  <div class="light-tabs" role="tablist" aria-label="${tr('三燈框架','Three-light framework')}">${D.lights.map(x=>`<button role="tab" id="light-${x.id}" aria-controls="light-panel" aria-selected="${x.id===l.id}" tabindex="${x.id===l.id?0:-1}" data-light="${x.id}" class="${x.id}"><span class="dot" aria-hidden="true"></span><span><b>${esc(tx(x.name))}</b><small>${esc(tx(x.label))}</small></span></button>`).join('')}</div>
  <div class="light-panel ${l.id}" id="light-panel" role="tabpanel" aria-labelledby="light-${l.id}" tabindex="0"><p class="eyebrow">${esc(tx(l.tag))}</p><h3>${esc(tx(l.label))}</h3><p>${esc(tx(l.definition))}</p><ul>${tx(l.examples).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><blockquote>${esc(tx(l.prompt))}</blockquote>${l.prompt2?`<blockquote>${esc(tx(l.prompt2))}</blockquote>`:''}<p class="light-note">${esc(tx(l.note))}</p>${source(l.source)}</div>
  <div class="ask-note"><span aria-hidden="true">?</span><p><strong>${tr('不清楚，先問老師。','Unsure? Ask your teacher first.')}</strong><br>${tr('不要自行假設可以使用，也不要把上一份功課的許可套用到這一份。','Do not assume permission or carry a previous assignment’s permission over to this one.')}</p></div></section>
  <section id="protect" class="guide-section"><div class="section-heading"><span class="section-no">03</span><div><p class="eyebrow">RESPONSIBILITY COMES WITH EVERY LIGHT</p><h2>${tr('每一種燈號，都有共同底線。','Every light comes with responsibility.')}</h2></div></div><p class="section-intro">${tr('不輸入敏感資料、不盲信生成內容、不侵犯他人權益、不利用 AI 傷害他人。','Do not enter sensitive information, blindly trust generated content, infringe others’ rights, or use AI to harm people.')}</p><div class="accordions">${D.safety.map((s,i)=>`<details ${i===0?'open':''}><summary><span>0${i+1}</span>${esc(tx(s.title))}<b aria-hidden="true">+</b></summary><div class="detail-body"><p>${esc(tx(s.intro))}</p><ul>${tx(s.items).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${source(s.source)}</div></details>`).join('')}</div></section>
  <section id="disclose" class="guide-section"><div class="section-heading"><span class="section-no">04</span><div><p class="eyebrow">MAKE YOUR LEARNING VISIBLE</p><h2>${tr('AI 幫了甚麼？你完成了甚麼？','What did AI do? What did you do?')}</h2></div></div><p class="section-intro">${tr('按教師及科組要求誠實說明，讓學習過程保持透明和公平。聲明不能代替書籍、網站、圖片及數據的來源引用。','Disclose AI use honestly as your teacher or department requires, keeping the learning process transparent and fair. Disclosure does not replace citations for books, websites, images or data.')}</p><div class="disclose-rows">${[[tr('使用工具','Tools used'),tr('名稱、使用日期或期間','Names and dates or period of use')],[tr('AI 如何協助我','How AI helped'),tr('用在哪個步驟，提供甚麼協助','Which step it supported and how')],[tr('我自己完成的部分','My own work'),tr('自己的分析、創作和判斷','Your analysis, creation and judgement')],[tr('我如何檢查或修改','How I checked or revised'),tr('方法與結果，包括尚未核實的部分','Methods and results, including anything unverified')]].map(([a,b],i)=>`<div><span>0${i+1}</span><h3>${a}</h3><p>${b}</p></div>`).join('')}</div><p>${tr('修改文字不等於核實事實。填寫聲明，也不代表原本的 AI 使用已獲准。','Revising wording does not verify facts. Completing a disclosure does not authorise the original AI use.')}</p>${source({zh:'附錄二：學生作品／課業申報表格',en:'Appendix II: Student work / assignment disclosure form'})}<a class="button primary" href="#declaration">${tr('整理我的 AI 使用聲明','Prepare my disclosure')} ${arrow}</a></section>
  <section class="next-banner"><p class="eyebrow">PUT IT INTO PRACTICE</p><h2>${tr('懂得規則，也試試判斷。','Know the rules. Practise the judgement.')}</h2><p>${tr('8 個校園情境，每題都有原因和相關指引。','Eight school scenarios, each with an explanation and a link to the guide.')}</p><a class="button primary" href="#practice">${tr('開始情境練習','Start practising')} →</a></section>
  <section class="cert-banner" aria-labelledby="certificate-heading"><div><p class="eyebrow">LIY FOUNDATION STAGE · SCHOOL ACCOUNT ASSESSMENT</p><h2 id="certificate-heading">${tr('完成入門階段，取得人工智能素養基礎證書','Complete the foundation stage and earn the AI Literacy Foundation Certificate')}</h2><p>${tr('全體學生均應完成本階段指定學習並通過測驗。測驗以學校 Google 帳戶登入，並按核定指引版本出題。','All students are expected to complete this stage’s designated learning and pass the assessment. Sign-in uses school Google accounts; questions follow the approved guideline version.')}</p></div>${C.policyApproved&&C.assessmentUrl?`<a class="button primary" href="${esc(C.assessmentUrl)}" target="_blank" rel="noopener noreferrer">${tr('登入並開始測驗','Sign in and begin')} ↗</a>`:`<div class="cert-pending"><span class="button secondary" aria-disabled="true">${tr('正式測驗準備中','Assessment preparing')}</span><small>${tr('待指引定稿及校內登入部署完成後開放','Opens after policy approval and school sign-in setup')}</small></div>`}</section></div></div>`;
 }
 function pageIntro(kicker,title,desc){return `<div class="page-intro wrap"><p class="eyebrow">${kicker}</p><h1>${title}</h1><p>${desc}</p></div>`;}
 function answerLabel(id){return {green:tr('綠燈・開放使用','Green · Open use'),yellow:tr('黃燈・有條件使用','Yellow · Conditional use'),red:tr('紅燈・禁止使用','Red · Prohibited use'),ask:tr('不確定・先問老師','Unclear · Ask the teacher')}[id];}
 function practice(){
  const intro=pageIntro('02 / SCENARIO PRACTICE',tr('把指引，放進真實情境。','Bring the guide into real situations.'),tr('先判斷，再看原因。這是幫助理解的練習，不是考試；答案只保留在本次頁面。','Make a judgement, then explore why. This is practice, not an exam. Answers stay only on this page.'));
  const done=state.q>=D.questions.length,score=state.answers.filter((a,i)=>a===D.questions[i].answer).length;
  if(done)return intro+`<div class="tool-layout wrap"><section class="practice-card"><p class="eyebrow">${tr('已完成全部情境','ALL SCENARIOS COMPLETED')}</p><h2>${tr('把原因帶走，比記住顏色更重要。','Take the reasoning with you.')}</h2><p class="score"><strong>${score}</strong> / 8 <span>${tr('題首次答對','correct first choices')}</span></p><p>${tr('完成練習不等於獲准在任何課業使用 AI。每項任務仍要看教師指示。','Completing the practice does not give permission to use AI on any assignment. Check the teacher’s instructions for each task.')}</p><div class="review-list">${D.questions.map((q,i)=>`<details><summary><span class="result-dot ${state.answers[i]===q.answer?'right':'wrong'}">${state.answers[i]===q.answer?'✓':'↻'}</span>${i+1}. ${esc(tx(q.theme))}</summary><div class="detail-body"><p>${esc(tx(q.text))}</p><p><strong>${answerLabel(q.answer)}</strong></p><p>${esc(tx(q.explain))}</p><a href="#${q.ref}" class="text-link">${tr('回看相關指引','Revisit the guide')} →</a></div></details>`).join('')}</div><div class="button-row"><button class="button secondary" data-action="restart">${tr('重新練習','Try again')}</button><a class="button primary" href="#check">${tr('檢查我自己的情況','Check my own situation')} →</a></div></section><aside class="tool-aside"><h3>${tr('記住這一句','KEEP THIS IN MIND')}</h3><p>${tr('燈號是針對學習任務，而不是某一項 AI 功能。','The light applies to the learning task, not to a particular AI feature.')}</p></aside></div>`;
  const q=D.questions[state.q],a=state.answers[state.q],answered=a!==undefined;
  return intro+`<div class="tool-layout wrap"><section class="practice-card"><div class="practice-meta"><span>${esc(tx(q.theme))}</span><span>${state.q+1} / 8</span></div><div class="progress-track" role="progressbar" aria-label="${tr('練習進度','Practice progress')}" aria-valuemin="0" aria-valuemax="8" aria-valuenow="${state.answers.length}"><i style="width:${state.answers.length/8*100}%"></i></div><h2 class="scenario">${esc(tx(q.text))}</h2><p class="muted">${tr('按這項任務的條件，選出最合適的判斷。','Choose the best judgement for the conditions of this task.')}</p><div class="answer-grid">${['green','yellow','red','ask'].map((id,i)=>`<button class="answer ${id} ${a===id?'chosen':''} ${answered&&q.answer===id?'correct':''}" data-answer="${id}" ${answered?'disabled':''}><span class="answer-letter">${String.fromCharCode(65+i)}</span><span>${answerLabel(id)}</span>${answered&&q.answer===id?'<span aria-hidden="true">✓</span>':''}</button>`).join('')}</div>${answered?`<div class="feedback ${a===q.answer?'right':'reflect'}" id="feedback" tabindex="-1" role="status"><strong>${a===q.answer?tr('判斷正確。','That’s right.'):tr('再想一想這個關鍵。','Here is the key distinction.')}</strong><p>${esc(tx(q.explain))}</p><a href="#${q.ref}" class="text-link">${tr('查看相關指引','See the relevant guide')} →</a></div><button class="button primary next-question" data-action="next">${state.q===7?tr('查看學習回顧','Review my practice'):tr('下一個情境','Next scenario')} →</button>`:''}</section><aside class="tool-aside"><span class="eyebrow">THINK BEFORE YOU CHOOSE</span><h3>${tr('先看任務，再看用法。','Task first. Use second.')}</h3><p>${tr('老師批准了甚麼？<br>哪些思考應由我完成？<br>有沒有涉及受保護資料？','What did the teacher approve?<br>What thinking must I do?<br>Is any protected information involved?')}</p><button class="text-link reset-link" data-action="restart">${tr('重新開始這組練習','Restart this practice')}</button></aside></div>`;
 }
 function checkItems(){const before=state.stage==='before';return [
  ['think',tr('先想','Think'),tr('我有先自己思考，並清楚哪些工作須由我完成嗎？','Have I thought for myself and identified the work I must do?')],
  ['verify',tr('查證','Verify'),before?tr('我已想好用哪些可信來源或方法查證 AI 內容嗎？','Have I planned credible sources or methods for checking AI’s content?'):tr('我已核實要提交或分享的 AI 內容及來源嗎？','Have I verified the AI content and sources I will submit or share?')],
  ['declare',tr('申報','Disclose'),before?tr('我清楚這項課業的申報要求，並會按要求記錄嗎？','Do I understand this task’s disclosure requirements and plan to record what is needed?'):tr('我已按教師或科組要求如實交代 AI 的使用嗎？','Have I honestly disclosed AI use as required by my teacher or department?')],
  ['teacher',tr('有疑問便問','Ask when unsure'),tr('老師已容許我這樣使用 AI，而且我清楚可用的範圍嗎？','Has my teacher allowed this use, and do I understand the permitted scope?')],
  ['privacy',tr('資料安全','Data safety'),before?tr('我打算輸入的內容，是否包含敏感、機密或受保護資料？','Will the content I enter include sensitive, confidential or protected information?'):tr('我是否曾輸入、上載或分享敏感、機密或受保護資料？','Have I entered, uploaded or shared sensitive, confidential or protected information?')]
 ];}
 function check(){return pageIntro('03 / PERSONAL SELF-CHECK',tr('停一停，檢查自己的做法。','Pause and check your approach.'),tr('按你的實際情況作答。自查提供下一步提醒，不代替教師的許可或判斷。','Answer for your actual situation. This check suggests next steps; it does not replace teacher permission or judgement.'))+`<div class="tool-layout wrap"><section class="check-card"><div class="stage-toggle" role="group" aria-label="${tr('使用階段','Stage of use')}"><button data-stage="before" aria-pressed="${state.stage==='before'}">${tr('開始使用前','Before using AI')}</button><button data-stage="after" aria-pressed="${state.stage==='after'}">${tr('使用後／提交前','After use / before submission')}</button></div><p class="stage-hint">${state.stage==='before'?tr('現在先確認方法與要求，不需要聲稱已完成尚未開始的查證或申報。','Plan your checks and understand the requirements. You do not need to claim you have already completed them.'):tr('回顧實際做過的事；還未完成的步驟，請如實作答。','Reflect on what you actually did. Be honest about anything unfinished.')}</p><form id="check-form">${checkItems().map(([id,label,q],i)=>`<div class="check-item"><label for="check-${id}"><span class="check-number">${i<4?'0'+(i+1):'!'}</span><span><small>${label}</small><strong>${q}</strong></span></label><select required id="check-${id}" name="${id}">${selectOptions([['',tr('請選擇','Select an answer')],['yes',tr('是','Yes')],['no',tr('否','No')],...(id==='declare'?[['not-required',tr('教師已說明不用申報','Teacher explicitly said no disclosure is needed')]]:[]),['unsure',tr('不確定','Not sure')]],state.checks[id]||'')}</select></div>`).join('')}<div class="button-row"><button class="button primary" type="submit">${tr('看看下一步','Show my next steps')} →</button><button class="button secondary" type="button" data-action="reset-check">${tr('清除答案','Clear answers')}</button></div></form><div id="check-output">${state.checkResult?checkResult():''}</div></section><aside class="tool-aside"><p class="eyebrow">FOUR HABITS + ONE BOUNDARY</p><h3>${tr('這不是「剔完就可以」。','A checklist is not permission.')}</h3><p>${tr('只要規則不清楚，先問任課老師。涉及敏感、機密或受保護資料時，任何燈號都不可上載。','If the rules are unclear, ask your teacher first. Never upload sensitive, confidential or protected information, whatever the light.')}</p>${source({zh:'第二部分・一及三；第一部分・四',en:'Part II · 1 and 3; Part I · 4'})}</aside></div>`;}
 function checkResult(){
  const c=state.checks,before=state.stage==='before',actions=[];
  if(c.privacy==='yes')actions.push(tr(before?'停止上載：移除敏感、機密或受保護資料，再向教師查詢適當做法。':'停止進一步分享，向教師說明已上載受保護資料的情況，尋求處理協助。',before?'Do not upload. Remove sensitive, confidential or protected information and ask your teacher how to proceed.':'Stop further sharing and tell your teacher that protected information was uploaded. Ask for help handling it.'));
  if(c.privacy==='unsure')actions.push(tr('先查清資料性質，不確定時不要輸入或上載，並向教師查詢。','Check the nature of the information. Do not enter or upload it while unsure; ask your teacher.'));
  if(c.teacher==='no')actions.push(tr('暫停這種 AI 使用方式，先取得教師對這項任務的明確指示。','Pause this AI use and obtain clear teacher instructions for this task.'));
  if(c.teacher==='unsure')actions.push(tr('先問任課老師可以用 AI 做哪些部分，不自行假設獲准。','Ask which parts may use AI. Do not assume permission.'));
  if(c.think!=='yes')actions.push(tr('先整理自己的想法及要展示的能力，調整會取代主要思考的使用方式。','Organise your own thinking and identify the ability you must demonstrate. Adjust any AI use that would replace it.'));
  if(c.verify!=='yes')actions.push(tr(before?'先訂好查證方法，例如課本、原始資料、重新計算或程式測試。':'提交或分享前補做查證；不能核實的內容要如實說明，不當作已確定的事實。',before?'Plan verification using textbooks, original sources, recalculation or code testing.':'Verify before submitting or sharing. Clearly identify anything unverified rather than presenting it as established fact.'));
  if(!['yes','not-required'].includes(c.declare))actions.push(tr(c.declare==='unsure'?'向教師確認是否需要申報及保留哪些紀錄。':before?'先安排保留課業要求的使用紀錄，準備按要求申報。':'補充教師要求的 AI 使用聲明，清楚區分 AI 協助與自己的工作。',c.declare==='unsure'?'Ask whether disclosure is needed and which records to retain.':before?'Plan to keep the required records and disclose as instructed.':'Complete the required disclosure, distinguishing AI assistance from your own work.'));
  const blocked=c.teacher!=='yes'||c.privacy!=='no';
  return `<section class="check-result ${blocked?'reflect':'right'}" id="check-feedback" tabindex="-1" role="status"><p class="eyebrow">${tr('你的下一步','YOUR NEXT STEPS')}</p><h2>${blocked?tr('先停一停，把界線問清楚。','Pause and clarify the boundaries.'):actions.length?tr('還有幾步，值得先做好。','A few steps still need attention.'):tr('你已完成這次自我檢查。','You have completed this self-check.')}</h2>${actions.length?`<ul>${actions.map(a=>`<li>${a}</li>`).join('')}</ul>`:`<p>${tr('繼續按教師指定的範圍學習，使用後仍要查證，並按要求申報。','Keep working within your teacher’s scope. Verify after use and disclose as required.')}</p>`}<p class="result-disclaimer">${tr('這是根據你填寫的答案提供的提醒，不代表獲准使用或已被判定合規。','These reminders are based on your answers. They do not grant permission or certify compliance.')}</p><a href="#declaration" class="text-link">${tr('需要申報？整理使用紀錄','Need to disclose? Prepare a record')} →</a></section>`;
 }
 function field(name,label,hint='',opts={}){
  const id='form-'+name,v=state.form[name]||'',req=opts.required?'required':'',description=hint?`aria-describedby="hint-${name}"`:'';
  let control=opts.select?`<select id="${id}" name="${name}" ${req} ${description}>${selectOptions(opts.select,v)}</select>`:opts.area?`<textarea id="${id}" name="${name}" rows="${opts.rows||3}" maxlength="4000" ${req} ${description}>${esc(v)}</textarea>`:`<input id="${id}" name="${name}" type="${opts.type||'text'}" value="${esc(v)}" maxlength="200" ${req} ${description}>`;
  return `<div class="form-field ${opts.wide?'wide':''}"><label for="${id}">${label}${opts.required?` <span class="required">${tr('必填','required')}</span>`:''}</label>${hint?`<p id="hint-${name}" class="field-hint">${hint}</p>`:''}${control}</div>`;
 }
 function declaration(){return pageIntro('04 / AI USE DISCLOSURE',tr('把你的學習過程，說清楚。','Tell the story of your learning.'),tr('依附錄二整理使用紀錄。按教師或科組要求申報；只寫實際做過的事，不用估算 AI 貢獻百分比。','Prepare a record using Appendix II. Disclose as your teacher or department requires. Describe what you actually did; no AI contribution percentage is needed.'))+`<div class="declaration-layout wrap"><section class="form-card"><div class="privacy-note"><span aria-hidden="true">◇</span><p>${tr('不用填姓名、班別或私人資料。文字只在這個頁面處理，不會傳送到 AI 服務；重新整理後清空，離開前請自行保存。','No name, class or private details are needed. Text is processed only on this page and is not sent to an AI service. Refreshing clears it; save your copy before leaving.')}</p></div><form id="disclosure-form" autocomplete="off"><h2>${tr('01　這是哪一項課業？','01　About the assignment')}</h2><div class="form-grid">
  ${field('subject',tr('科目','Subject'),' ',{required:true})}${field('assignment',tr('課業名稱','Assignment title'),'',{required:true})}${field('date',tr('填寫日期','Date'),'',{type:'date'})}
  ${field('light',tr('教師指定燈號','Teacher’s task label'),'',{required:true,select:[['',tr('請選擇','Select a label')],['green',answerLabel('green')],['yellow',answerLabel('yellow')],['red',answerLabel('red')],['unsure',tr('不確定','Not sure')]]})}
  ${field('instructions',tr('教師的使用範圍或申報要求','Teacher’s scope or disclosure requirements'),tr('如不清楚，可如實填寫「待向教師確認」。','If unclear, you may write “To be confirmed with the teacher”.'),{area:true,wide:true,rows:2})}</div>
  <h2>${tr('02　AI 與你，各做了甚麼？','02　What did AI do, and what did you do?')}</h2><div class="form-grid">${field('tools',tr('使用工具','Tools used'),tr('可填多於一項，按實際使用填寫。','List one or more tools you actually used.'),{required:true})}${field('period',tr('使用日期或期間','Dates or period of use'))}${field('help',tr('AI 如何協助我','How AI helped me'),tr('用在哪個步驟或部分？提供了甚麼協助？','Which step or part did it support? What assistance did it provide?'),{area:true,required:true,wide:true})}${field('own',tr('我自己完成的部分','The parts I completed myself'),tr('描述自己的分析、創作或判斷；可說明採用或拒絕哪些建議。','Describe your analysis, creation or judgement, including suggestions you accepted or rejected.'),{area:true,required:true,wide:true})}</div>
  <h2>${tr('03　如何檢查或修改？','03　How did you check or revise?')}</h2><div class="form-grid">${field('verifyStatus',tr('查證進度','Verification status'),'',{required:true,wide:true,select:[['',tr('請選擇','Select status')],['checked',tr('已查證本次使用的相關內容','I checked the relevant content I used')],['partial',tr('只完成部分查證','Only partly verified')],['notyet',tr('尚未查證','Not yet verified')]]})}${field('verification',tr('檢查／修改的方法與結果','Checking / revision methods and results'),tr('列出來源、重算、測試或修改的結果；尚未核實也要說明。修改文字不等於核實事實。','Describe sources, recalculation, testing or revisions and their results. Include anything unverified. Revising wording does not verify facts.'),{area:true,required:true,wide:true})}${field('evidence',tr('按教師要求附上的紀錄','Records attached as the teacher requires'),tr('只列出附件名稱或內容簡述，不要在這裡上載文件。未要求可填「不適用」。','List attachment names or a short description; do not upload files here. If not required, write “Not applicable”.'),{area:true,wide:true,rows:2})}</div>
  <label class="confirm"><input type="checkbox" name="confirm" ${state.form.confirm?'checked':''} required><span>${tr('我已核對以上內容，按實際使用情況填寫，並如實說明自己完成的工作及尚未核實的部分。','I have checked these entries against my actual AI use, honestly describing my own work and anything not yet verified.')}</span></label>
  <div class="button-row"><button class="button primary" type="submit">${tr('整理成聲明','Prepare disclosure')} →</button><button class="button secondary" type="button" data-action="reset-form">${tr('清空表格','Clear form')}</button></div></form></section>
  <aside class="preview-card"><div class="preview-top"><p class="eyebrow">YOUR LEARNING RECORD</p><span class="paper-tag">${state.lang==='zh'?'中文':'ENGLISH'}</span></div><h2>${tr('聲明預覽','Disclosure preview')}</h2><p>${tr('可以複製到課業、下載文字，或列印／儲存成 PDF。','Copy into your work, download as text, or print / save as PDF.')}</p><div id="declaration-output">${preview()}</div><div class="export-actions"><button class="button primary" data-action="copy" ${state.generated?'':'disabled'}>${tr('複製文字','Copy text')}</button><button class="button secondary" data-action="download" ${state.generated?'':'disabled'}>${tr('下載 TXT','Download TXT')}</button><button class="button secondary" data-action="print" ${state.generated?'':'disabled'}>${tr('列印／PDF','Print / PDF')}</button></div><p id="export-status" role="status" class="export-status"></p><p class="source-ref">${tr('依據附錄二・學生作品／課業申報表格。英文為輔助翻譯。','Based on Appendix II, the student work / assignment disclosure form. English is a supporting translation.')}</p><p class="preview-footnote">${tr('如已超出獲准範圍，請先向教師說明。填寫聲明不代表使用已獲准。一般資料引用仍須另按課業要求處理。','If your use exceeded the permitted scope, speak to your teacher first. Disclosure does not grant permission. Cite other sources separately as required.')}</p></aside></div>`;}
 function disclosureText(){
  const f=state.form,status={checked:tr('已查證本次使用的相關內容','I checked the relevant content I used'),partial:tr('只完成部分查證','Only partly verified'),notyet:tr('尚未查證','Not yet verified')}[f.verifyStatus];
  const optional=v=>v?.trim()||tr('未填寫','Not provided');
  const rows=[tx(D.school),tr('學生作品／課業 AI 使用聲明','AI use disclosure for student work / assignments'),tr('依據校本指引初稿 v1','Based on school guidelines, draft v1'),''];
  const warning=declarationWarning();if(warning)rows.push(tr('注意：','Note: ')+warning,'');
  const fields=[[tr('科目','Subject'),f.subject],[tr('課業名稱','Assignment title'),f.assignment],[tr('填寫日期','Date'),optional(f.date)],[tr('教師指定燈號','Teacher’s task label'),f.light==='unsure'?tr('不確定','Not sure'):answerLabel(f.light)],[tr('教師的使用範圍或申報要求','Teacher’s scope or disclosure requirements'),optional(f.instructions)],[tr('使用工具','Tools used'),f.tools],[tr('使用日期或期間','Dates or period of use'),optional(f.period)],[tr('AI 如何協助我','How AI helped me'),f.help],[tr('我自己完成的部分','The parts I completed myself'),f.own],[tr('查證進度（學生自述）','Verification status (self-reported)'),status],[tr('我如何檢查或修改 AI 的內容','How I checked or revised AI’s content'),f.verification],[tr('按教師要求附上的紀錄','Records attached as the teacher requires'),optional(f.evidence)]];
  fields.forEach(([a,b])=>rows.push(a+'：',b.trim(),''));
  rows.push(tr('聲明','Declaration'),tr('以上內容按我的實際使用情況填寫。我已區分 AI 的協助與自己完成的工作，並如實交代已完成及尚未完成的核實；沒有把 AI 完成的部分冒認為自己獨立完成。','These entries reflect my actual use. I have distinguished AI assistance from my own work and honestly described completed and outstanding verification. I have not presented AI-completed parts as work I completed independently.'),'',tr('如已超出獲准範圍，請先向教師說明。填寫本表不代表使用已獲准。一般資料引用仍須另按課業要求處理。','If your use exceeded the permitted scope, speak to your teacher first. Completing this form does not grant permission. Other sources must still be cited as required.'));
  return rows.join('\n');
 }
 function declarationWarning(){const f=state.form,parts=[];
  if(['red','unsure'].includes(f.light))parts.push(tr('本紀錄涉及紅燈或尚未確定的使用要求，請先向教師說明。','This record involves a red label or unclear requirements. Speak to your teacher first.'));
  if(['partial','notyet'].includes(f.verifyStatus))parts.push(tr('仍有內容尚未查證；請如實交代，提交或分享前補做查證。','Some content remains unverified. Disclose this honestly and verify before submitting or sharing.'));
  return parts.join(' ');
 }
 function preview(){if(!state.generated)return `<div class="empty-preview"><span aria-hidden="true">✎</span><h3>${tr('先填寫，再整理。','Fill in, then prepare.')}</h3><p>${tr('你的聲明會在這裡出現。系統不會代你推斷或補寫使用經歷。','Your disclosure will appear here. The tool does not infer or invent your experience.')}</p></div>`;return `${declarationWarning()?`<div class="form-warning" role="status">${esc(declarationWarning())}</div>`:''}<label class="sr-only" for="disclosure-text">${tr('可複製的聲明文字','Disclosure text to copy')}</label><textarea id="disclosure-text" readonly rows="19">${esc(disclosureText())}</textarea><p class="generated-note">${tr('切換語言會翻譯欄位與固定句式，不會翻譯或改寫你輸入的內容。','Language switching translates labels and fixed wording, not your own entries.')}</p>`;}

 function render(focusId){
  document.documentElement.lang=state.lang==='zh'?'zh-Hant':'en';
  document.title=tr('LIY學生數字素養計劃｜入門階段｜李賢堯紀念中學','LIY Student Digital Literacy Programme | Foundation Stage');
  const pages={guide,practice,check,declaration};app.innerHTML=shell(pages[route()]());
  if(focusId)document.getElementById(focusId)?.focus({preventScroll:true});
 }
 function invalidateForm(){state.generated=false;const output=document.getElementById('declaration-output');if(output)output.innerHTML=preview();document.querySelectorAll('.export-actions button').forEach(b=>b.disabled=true);const status=document.getElementById('export-status');if(status)status.textContent='';}
 function resetCheck(){state.checks={};state.checkResult=false;render();}
 app.addEventListener('input',e=>{
  if(e.target.closest('#disclosure-form')){state.form[e.target.name]=e.target.type==='checkbox'?e.target.checked:e.target.value;invalidateForm();}
  if(e.target.closest('#check-form')){state.checks[e.target.name]=e.target.value;state.checkResult=false;document.getElementById('check-output').innerHTML='';}
 });
 app.addEventListener('change',e=>{
  if(e.target.closest('#disclosure-form')){state.form[e.target.name]=e.target.type==='checkbox'?e.target.checked:e.target.value;invalidateForm();}
  if(e.target.closest('#check-form')){state.checks[e.target.name]=e.target.value;state.checkResult=false;document.getElementById('check-output').innerHTML='';}
 });
 app.addEventListener('submit',e=>{
  e.preventDefault();
  if(e.target.id==='check-form'){state.checkResult=true;document.getElementById('check-output').innerHTML=checkResult();document.getElementById('check-feedback').focus();}
  if(e.target.id==='disclosure-form'){
   const required=['subject','assignment','tools','help','own','verification'];
   const blank=required.find(n=>!state.form[n]?.trim());
   if(blank){const f=document.getElementById('form-'+blank);f.setCustomValidity(tr('請填寫實際內容，不能只輸入空格。','Please enter actual content, not only spaces.'));f.reportValidity();f.addEventListener('input',()=>f.setCustomValidity(''),{once:true});return;}
   state.generated=true;document.getElementById('declaration-output').innerHTML=preview();document.querySelectorAll('.export-actions button').forEach(b=>b.disabled=false);document.getElementById('disclosure-text').focus();
  }
 });
 app.addEventListener('click',async e=>{
  const b=e.target.closest('button');if(!b)return;
  if(b.dataset.habit){state.habit=b.dataset.habit;render('tab-'+state.habit);return;}
  if(b.dataset.light){state.light=b.dataset.light;render('light-'+state.light);return;}
  if(b.dataset.answer&&state.answers[state.q]===undefined){state.answers[state.q]=b.dataset.answer;render('feedback');return;}
  if(b.dataset.stage){if(state.stage!==b.dataset.stage){state.stage=b.dataset.stage;delete state.checks.verify;delete state.checks.declare;state.checkResult=false;render();document.querySelector(`[data-stage="${state.stage}"]`).focus({preventScroll:true});}return;}
  const action=b.dataset.action;
  if(action==='language'){state.lang=state.lang==='zh'?'en':'zh';render();document.querySelector('.language').focus({preventScroll:true});}
  if(action==='next'){state.q++;render();document.querySelector('.scenario, .practice-card h2')?.setAttribute('tabindex','-1');document.querySelector('.scenario, .practice-card h2')?.focus();}
  if(action==='restart'){state.q=0;state.answers=[];render();}
  if(action==='reset-all'){state.habit='think';state.light='green';state.q=0;state.answers=[];state.stage='before';state.checks={};state.checkResult=false;state.form={light:'',verifyStatus:''};state.generated=false;document.getElementById('print-area').textContent='';render();document.getElementById('main').focus({preventScroll:true});window.scrollTo(0,0);}
  if(action==='reset-check')resetCheck();
  if(action==='reset-form'){state.form={light:'',verifyStatus:''};state.generated=false;render();document.getElementById('form-subject').focus();}
  if(['copy','download','print'].includes(action)&&!state.generated)return;
  if(action==='copy'){
   try{if(!navigator.clipboard?.writeText)throw Error('Clipboard unavailable');await navigator.clipboard.writeText(disclosureText());document.getElementById('export-status').textContent=tr('已複製聲明文字。','Disclosure copied.');}
   catch{const field=document.getElementById('disclosure-text');field.focus();field.select();document.getElementById('export-status').textContent=tr('未能自動複製；已選取文字，請按 ⌘C／Ctrl+C 或長按複製。','Automatic copying was unavailable. Text is selected: use ⌘C / Ctrl+C or long-press to copy.');}
  }
  if(action==='download'){
   const blob=new Blob(['\uFEFF'+disclosureText()],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=state.lang==='zh'?'AI使用聲明.txt':'AI-use-disclosure.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);document.getElementById('export-status').textContent=tr('已準備文字檔下載；請查看瀏覽器的下載項目。','The text download is ready. Check your browser downloads.');
  }
  if(action==='print'){
   document.getElementById('print-area').textContent=disclosureText();document.body.classList.add('printing-disclosure');window.print();
  }
 });
 window.addEventListener('afterprint',()=>document.body.classList.remove('printing-disclosure'));
 app.addEventListener('keydown',e=>{
  const tab=e.target.closest('[role="tab"]');if(!tab||!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;
  e.preventDefault();const group=tab.closest('[role="tablist"]'),tabs=[...group.querySelectorAll('[role="tab"]')],i=tabs.indexOf(tab),next=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[next].click();
 });
 window.addEventListener('hashchange',()=>{render();const id=location.hash.slice(1);if(['habits','lights','protect','disclose'].includes(id)){document.getElementById(id)?.scrollIntoView();}else{window.scrollTo(0,0);document.getElementById('main')?.focus({preventScroll:true});}});
 render();
 if(['habits','lights','protect','disclose'].includes(location.hash.slice(1)))requestAnimationFrame(()=>document.getElementById(location.hash.slice(1))?.scrollIntoView());
})();
