/* Bilingual student guidance and learning activities. */
window.AI_CONTENT = (() => {
 const b = (zh,en) => ({zh,en});
 return {
 school:b('中華傳道會李賢堯紀念中學','CNEC Lee I Yao Memorial Secondary School'),
 principles:[b('誠信','Integrity'),b('明辨','Discernment'),b('創新','Innovation')],
 habits:[
  {id:'think',label:b('先想','Think first'),title:b('先自己思考，再請 AI 幫忙。','Start with your thinking. Then ask AI.'),
   body:b('在詢問 AI 前，先嘗試運用自己的知識、經驗和思考處理問題。AI 可以提供提示、解釋或不同角度，但你應保留自己的思考過程，不應把整項學習任務直接交給 AI 完成。','Before asking AI, try using your own knowledge, experience and reasoning. AI can offer hints, explanations or a different perspective. Keep your own thinking process; do not hand the entire learning task to AI.'),
   action:b('先寫下：我知道甚麼？我卡在哪一步？','Write down: What do I know? Where am I stuck?'),source:b('第二部分・一（一）','Part II · 1(a)')},
  {id:'verify',label:b('查證','Verify'),title:b('說得合理，未必說得正確。','Plausible does not always mean correct.'),
   body:b('利用課本、教師提供的資料及其他可信來源，核實 AI 的事實、數據、推論、引文、計算及圖像。留意資料的來源、時效和可能存在的偏見；提交或分享前，先作基本事實查證。','Use textbooks, teacher-provided materials and other credible sources to check AI-generated facts, data, reasoning, quotations, calculations and images. Consider sources, currency and potential bias. Fact-check before submitting or sharing.'),
   action:b('找原始來源、重新計算，或實際測試程式。','Find the original source, recalculate, or test the code.'),source:b('第二部分・一（二）','Part II · 1(b)')},
  {id:'declare',label:b('申報','Disclose'),title:b('讓自己的學習過程看得見。','Make your learning process visible.'),
   body:b('如課業涉及 AI 協助，須按照教師或科組要求說明使用情況。申報的目的是保持透明和公平。AI 使用申報不能取代資料引用；書籍、網站、圖片、數據及他人作品仍須按要求列明來源。','If AI assists with coursework, describe its use as required by your teacher or subject department. Disclosure supports transparency and fairness. It does not replace source citation: credit books, websites, images, data and other people’s work as required.'),
   action:b('說明 AI 幫了甚麼、自己做了甚麼、如何查證。','Explain what AI did, what you did, and how you checked.'),source:b('第二部分・一（三）；附錄二','Part II · 1(c); Appendix II')},
  {id:'ask',label:b('有疑問便問','Ask when unsure'),title:b('不清楚範圍，先問任課老師。','Unsure about the scope? Ask your teacher.'),
   body:b('如果不確定某項課業是否可以使用 AI，或不知道可以使用至甚麼程度，先向任課老師查詢，不應自行假設可以使用。個別任務的安排以任課教師及科組的具體指示為準。','If you are unsure whether AI is allowed or to what extent, ask your subject teacher first. Do not assume permission. Follow your teacher’s or subject department’s specific instructions for the task.'),
   action:b('可以問：「這項課業可以用 AI 做哪些部分？」','Ask: “Which parts of this task may I use AI for?”'),source:b('第二部分・一（四）；第一部分・二','Part II · 1(d); Part I · 2')}
 ],
 lights:[
  {id:'green',name:b('綠燈','Green'),label:b('開放使用','Open use'),tag:b('擴闊理解，仍須查證','Explore, and still verify'),
   definition:b('在不影響學術誠信及學習目標的情況下，AI 可作為學習輔助工具，但學生仍須自行判斷及查證內容。','AI may support learning when academic integrity and the learning objectives are maintained. Students must still use their own judgement and verify the content.'),
   examples:b(['解釋概念、提供提示或不同例子','腦力激盪、整理已學內容','提出問題、自擬練習','比較不同觀點、協助自主學習'],['Explain concepts; offer hints or different examples','Brainstorm and organise material already learned','Ask questions and create practice exercises','Compare perspectives and support independent learning']),
   prompt:b('「我不明白甚麼是動量守恆，可以用中學生程度再解釋一次嗎？」','“I don’t understand conservation of momentum. Could you explain it at secondary-school level?”'),
   prompt2:b('「根據我下面的筆記，替我設計五條問題，測試自己是否真的理解。」','“Using my notes below, create five questions to test whether I really understand.”'),
   note:b('即使屬於綠燈，也要查證 AI 提供的內容；申報按教師及科組要求。','Even under green, verify AI’s content. Follow your teacher’s or department’s disclosure requirements.'),source:b('第二部分・二「綠燈」及一（三）','Part II · 2, Green; 1(c)')},
  {id:'yellow',name:b('黃燈','Yellow'),label:b('有條件使用','Conditional use'),tag:b('先確認批准，再守住界線','Confirm permission; stay within scope'),
   definition:b('只可在教師明確批准及指定範圍內使用，不得取代學生需要展示的主要思考、分析、判斷或創作能力。','Use AI only with explicit teacher approval and within the specified scope. It must not replace the main thinking, analysis, judgement or creative ability you need to demonstrate.'),
   examples:b(['構思文章或報告方向、整理資料重點','提供修改建議、比較不同解決方案','協助專題方向設計、改善部分表達方式'],['Plan the direction of an essay or report; organise key information','Suggest revisions and compare possible solutions','Help shape a project direction or improve selected expressions']),
   prompt:b('教師指示：「可用作構思及整理資料，但最終論點、分析及文章必須由學生自行完成。」','Teacher instruction: “AI may help with brainstorming and organising information. The final arguments, analysis and writing must be your own.”'),
   note:b('教师可要求保留重要對話、標示 AI 協助部分、說明修改、反思建議或提交思考過程。是否申報及所需紀錄，按教師或科組要求。'.replace('教师','教師'),'Your teacher may ask for key conversations, identified AI-assisted parts, an explanation of revisions, reflection, or process evidence. Follow the teacher’s or department’s requirements for disclosure and records.'),source:b('第二部分・二「黃燈」；第三部分・二','Part II · 2, Yellow; Part III · 2')},
  {id:'red',name:b('紅燈','Red'),label:b('禁止使用','Prohibited use'),tag:b('保留應由自己展示的能力','Protect the ability you must demonstrate'),
   definition:b('如 AI 的使用會取代該項任務需要評估的學生能力，或涉及作弊、私隱、安全及其他不當用途，均不得使用。','AI use is prohibited if it replaces the student ability being assessed, or involves cheating, privacy, safety or other inappropriate uses.'),
   examples:b(['直接提交 AI 生成的完整答案或作品、利用 AI 代做課業','在測驗、考試或其他禁止使用 AI 的評估中使用','偽造資料、數據、引文或參考資料','冒充他人，製作或散播虛假、欺凌、深偽或有害內容','輸入或上載敏感、機密或受保護資料'],['Submit complete AI-generated answers or work; have AI do your coursework','Use AI in tests, exams or other assessments where it is prohibited','Fabricate information, data, quotations or references','Impersonate others or create or spread false, bullying, deepfake or harmful content','Enter or upload sensitive, confidential or protected information']),
   prompt:b('課業標示：「本課業用作評估學生個人能力，不得使用任何生成式 AI 完成任何部分。」','Task label: “This work assesses your individual ability. Generative AI must not be used to complete any part.”'),
   note:b('涉及學術不誠實，將按學校現行校規及相關評估規定處理。填寫聲明不代表使用已獲准。','Academic dishonesty is handled under existing school rules and assessment regulations. Filing a disclosure does not grant permission.'),source:b('第二部分・二「紅燈」；附錄一、二','Part II · 2, Red; Appendices I–II')}
 ],
 safety:[
  {title:b('資料有界線：這些不要上載','Know the boundary: do not upload these'),
   intro:b('任何時候都不要輸入、上載或分享敏感、機密或受保護資料，包括：','Never enter, upload or share sensitive, confidential or protected information, including:'),
   items:b(['身分證號碼、電話、住址等個人資料','帳戶密碼或登入資料','學生成績及個人評語','可識別個人身分的敏感相片、影片或錄音','未公開的試卷及評估材料','學校內部或機密文件','其他受保護的個人或學校資料'],['Personal information such as identity numbers, phone numbers and addresses','Passwords and login credentials','Student grades and individual comments','Sensitive photos, videos or recordings that identify someone','Unreleased examination papers and assessment materials','Internal or confidential school documents','Other protected personal or school information']),source:b('第一部分・四（一）；第二部分・三','Part I · 4(a); Part II · 3')},
  {title:b('尊重他人，也尊重作品來源','Respect people and the sources of work'),intro:b('尊重作品與創意、版權、私隱，以及他人的肖像與聲音。不得利用 AI 冒充、欺騙、欺凌或傷害他人，亦不得製作或散播虛假、深偽、色情、仇恨或其他有害內容。','Respect creative work, copyright, privacy, and people’s images and voices. Do not use AI to impersonate, deceive, bully or harm anyone, or create or spread false, deepfake, pornographic, hateful or other harmful content.'),
   items:b(['分享之前，考慮真確性、他人感受及自己的數碼足跡。','AI 使用申報不能代替資料引用。'],['Before sharing, consider truthfulness, the impact on others and your digital footprint.','Disclosing AI use does not replace citing sources.']),source:b('第一部分・四（二）；第二部分・一（三）','Part I · 4(b); Part II · 1(c)')},
  {title:b('為自己提交及分享的內容負責','Take responsibility for what you submit and share'),intro:b('AI 並非可靠資料來源的保證。重要資料應核實原始來源，並留意準確性、合理性、時效及偏見。無論是否使用 AI，你均須為最終內容負責。','AI is not a guarantee of a reliable source. Verify important information against original sources and consider accuracy, plausibility, currency and bias. You are responsible for the final content, whether or not you used AI.'),
   items:b(['找到原文，確認它真的支持所引用的說法。','計算結果自己重算；生成圖像也要檢查。','尚未查證，先查證再提交或分享。'],['Locate the original and check that it supports the claim.','Recalculate results and check generated images too.','If you have not verified the content, do so before submitting or sharing.']),source:b('第一部分・三（二）；第二部分・一（二）','Part I · 3(b); Part II · 1(b)')}
 ],
 questions:[
  {id:'q1',theme:b('理解概念','Understanding'),text:b('老師把自主溫習列為開放使用。你請 AI 以中學生程度解釋動量守恆，再用課本核對。這次使用屬於哪一類？','Your teacher labels independent revision as open use. You ask AI to explain conservation of momentum at secondary-school level, then check your textbook. Which category applies?'),answer:'green',explain:b('這是支援理解的綠燈情境；你仍須自己思考及查證，不能因為開放使用便盡信答案。','This is green: AI supports understanding. You must still think and verify; open use does not make every answer trustworthy.'),ref:'lights'},
  {id:'q2',theme:b('保留自己的思考','Your own thinking'),text:b('老師准許 AI 協助構思報告，但最終論點、分析及文章要自己完成。你請 AI 提供三個方向，再自行選擇、查證及寫作。','Your teacher allows AI to suggest report directions, but requires your own arguments, analysis and writing. You ask for three directions, then choose, verify and write for yourself.'),answer:'yellow',explain:b('老師已明確批准並指定範圍，因此屬黃燈。是否申報及保留對話，仍要按這份課業的指示。','This is yellow because the teacher explicitly approved a defined scope. Follow this task’s disclosure and conversation-record requirements.'),ref:'lights'},
  {id:'q3',theme:b('資料私隱','Privacy'),text:b('老師容許 AI 協助整理專題資料。你打算上載一份列有同學姓名、電話、成績及個人評語的表格，請 AI 分類。','AI is allowed to help organise project material. You plan to upload a table with classmates’ names, phone numbers, grades and personal comments for AI to categorise.'),answer:'red',explain:b('容許整理資料並不代表可以上載受保護資料。電話、成績及個人評語都在指引列出的禁止上載範圍內。','Permission to organise material does not permit uploading protected information. Phone numbers, grades and individual comments are explicitly listed as information not to upload.'),ref:'protect'},
  {id:'q4',theme:b('任務決定燈號','The task matters'),text:b('上一份專題可以用 AI 潤飾語文。今次是評估個人語文能力的寫作，老師未說明 AI 的使用範圍。你想沿用上次的方法。','AI proofreading was allowed for a previous project. This task assesses your own language ability, but the teacher has not specified the AI rules. You want to do the same as before.'),answer:'ask',explain:b('燈號針對任務，不是某項 AI 功能。不可把上一次的許可套用到這次；先詢問老師，不自行假設可以。','The category depends on the task, not the AI feature. Previous permission does not automatically apply. Ask your teacher first.'),ref:'lights'},
  {id:'q5',theme:b('自主練習','Independent practice'),text:b('在老師開放使用的自主溫習中，你用自己整理、沒有受保護資料的筆記，請 AI 設計五條練習題，自己作答再查證答案。','During open-use independent revision, you provide your own notes with no protected information and ask AI for five practice questions. You answer them yourself and check the answers.'),answer:'green',explain:b('自擬練習可以支援自主學習。使用自己的筆記也要檢查是否包含不可上載的資料，AI 答案亦須核實。','Creating exercises can support independent learning. Even your own notes need a check for protected information, and AI’s answers still need verification.'),ref:'habits'},
  {id:'q6',theme:b('學術誠信','Academic integrity'),text:b('你把課業題目交給 AI，直接提交它生成的完整文章，只在最後加一句「曾使用 AI」。','You give AI the assignment prompt and submit its complete essay, adding only “AI was used” at the end.'),answer:'red',explain:b('直接提交 AI 生成的完整作品，屬指引列出的禁止用途。申報不能把代做課業變成自己的學習成果，也不等於獲准使用。','Submitting complete AI-generated work is prohibited by the guideline. Disclosure does not turn outsourced work into your learning or grant permission.'),ref:'lights'},
  {id:'q7',theme:b('有條件使用','Conditional use'),text:b('老師明確准許 AI 對你已寫好的專題報告提出修改建議，要求保留重要對話並說明修改原因。你自己判斷及修改，按要求交代過程。','The teacher explicitly permits AI feedback on your draft project report and asks for key conversations and reasons for revisions. You judge and revise it yourself, documenting the process as required.'),answer:'yellow',explain:b('這次使用符合教師批准的範圍，亦保留了自己的判斷。黃燈的具體條件要逐項遵守。','You are working within the approved scope and retaining your judgement. Follow each condition specified for this yellow task.'),ref:'disclose'},
  {id:'q8',theme:b('尊重與數碼足跡','Respect and digital footprint'),text:b('同學說只是開玩笑，想用 AI 模仿另一位同學的聲音，製作他從未說過的話並放到群組。','A classmate says it is just a joke and wants to imitate another student’s voice with AI, making them say something they never said and posting it in a group chat.'),answer:'red',explain:b('冒充他人及製作或散播深偽、有害內容，屬禁止用途。「開玩笑」不能消除對他人的影響。','Impersonating someone or making or sharing deepfake or harmful content is prohibited. Calling it a joke does not remove its impact on others.'),ref:'protect'}
 ]
 };
})();
